# Generated by Django 3.2.22 on 2023-10-18 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shifts',
            new_name='Shift',
        ),
    ]
