# Generated by Django 3.2.22 on 2023-10-19 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_rename_shifts_shift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='mounth_id',
            new_name='mounth',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='worker_id',
            new_name='worker',
        ),
    ]
