# Generated by Django 3.2.22 on 2023-10-19 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_auto_20231019_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='mounth',
        ),
        migrations.DeleteModel(
            name='Mounth',
        ),
    ]
